const publicCmsScript = document.createElement('script');
publicCmsScript.src = './public-cms.js';
document.head.appendChild(publicCmsScript);
(function () {
  'use strict';
  const client = window.supabaseClient;
  if (!client) return;
  const collectionRows = { projects: [], skills: [], services: [], journey: [] };
  const realtimeTables = new Set(['projects', 'skills', 'services', 'journey', 'profile', 'site_settings']);
  const escape = value => String(value ?? '').replace(/[&<>"']/g, character => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#039;' }[character]));
  const list = value => Array.isArray(value) ? value : String(value || '').split(',').map(item => item.trim()).filter(Boolean);
  const published = table => client.from(table).select('*').eq('is_published', true).order('sort_order', { ascending:true }).order('created_at', { ascending:false });
  const text = (selector, value) => { const node = document.querySelector(selector); if (node && value != null && value !== '') node.textContent = value; };
  const imageUrl = value => value ? (/^https?:\/\//i.test(value) ? value : client.storage.from('portfolio-images').getPublicUrl(value).data.publicUrl) : '';
  function projects(rows) { const grid = document.querySelector('.projects-modern-grid'); if (!grid) return; grid.querySelectorAll('[data-supabase-content="projects"]').forEach(node => node.remove()); grid.insertAdjacentHTML('beforeend', rows.map(row => '<article data-supabase-content="projects" data-supabase-id="' + escape(row.id) + '" class="proj-modern-card" data-category="' + escape((row.category || '').toLowerCase()) + '"><div class="proj-mockup-wrapper"><div class="proj-category-badge">' + escape(row.category || 'Project') + '</div></div><div class="proj-card-content"><div class="proj-tech-stack">' + list(row.technologies).map(item => '<span class="proj-tech-pill">' + escape(item) + '</span>').join('') + '</div><h3 class="proj-card-title">' + escape(row.title) + '</h3><p class="proj-card-desc">' + escape(row.short_description || row.full_description) + '</p><div class="proj-card-footer">' + (row.live_url ? '<a href="' + escape(row.live_url) + '" target="_blank" rel="noopener" class="proj-footer-btn live">Live Preview</a>' : '') + (row.github_url ? '<a href="' + escape(row.github_url) + '" target="_blank" rel="noopener" class="proj-footer-btn github">GitHub</a>' : '') + '</div></div></article>').join('')); }
  function skills(rows) { const cloud = document.querySelector('.tech-cloud'); if (cloud) { cloud.querySelectorAll('[data-supabase-content="skills"]').forEach(node => node.remove()); cloud.insertAdjacentHTML('beforeend', rows.map(row => '<div data-supabase-content="skills" data-supabase-id="' + escape(row.id) + '" class="tech-pill-tag"><span>' + escape(row.icon || '•') + '</span><span>' + escape(row.name) + '</span></div>').join('')); } const grid = document.querySelector('.skills-progress-grid'); if (grid) { grid.querySelectorAll('[data-supabase-content="skills"]').forEach(node => node.remove()); grid.insertAdjacentHTML('beforeend', rows.map(row => '<div data-supabase-content="skills" data-supabase-id="' + escape(row.id) + '" class="skill-progress-item"><div class="skill-info"><span class="skill-name">' + escape(row.icon || '•') + ' ' + escape(row.name) + '</span><span class="skill-perc">' + Number(row.level || 0) + '%</span></div><div class="progress-bar-bg"><div class="progress-bar-fill" style="width:' + Math.max(0, Math.min(100, Number(row.level || 0))) + '%"></div></div></div>').join('')); } }
  function services(rows) { const grid = document.querySelector('.services-grid'); if (!grid) return; grid.querySelectorAll('[data-supabase-content="services"]').forEach(node => node.remove()); grid.insertAdjacentHTML('beforeend', rows.map(row => '<div data-supabase-content="services" class="service-card"><div class="service-icon">' + escape(row.icon || '✦') + '</div><div class="service-title">' + escape(row.title) + '</div><div class="service-desc">' + escape(row.description) + '</div><ul class="service-list">' + list(row.features).map(item => '<li>' + escape(item) + '</li>').join('') + '</ul><a href="#contact" class="service-cta">Get Quote</a></div>').join('')); }
  function journey(rows) { const columns = document.querySelectorAll('#journey .journey-grid > div'); if (!columns.length) return; const groups = [rows.filter(row => /education/i.test(row.type)), rows.filter(row => !/education/i.test(row.type))]; columns.forEach((column, index) => { const timeline = column.querySelector('.timeline'); if (!timeline) return; timeline.querySelectorAll('[data-supabase-content="journey"]').forEach(node => node.remove()); timeline.insertAdjacentHTML('beforeend', groups[index].map(row => '<article data-supabase-content="journey" class="timeline-item"><div class="timeline-date">' + escape([row.start_date,row.end_date].filter(Boolean).join(' - ')) + '</div><h3 class="timeline-title">' + escape(row.title) + '</h3><div class="timeline-sub">' + escape([row.organization,row.location].filter(Boolean).join(' · ')) + '</div><p class="timeline-desc">' + escape(row.description) + '</p></article>').join('')); }); }
  function profile(row) { if (!row) return; text('.bento-profile-name', row.name); text('.bento-profile-role', row.short_bio); text('.about-hero-subtitle', row.short_bio); text('.spec-item:nth-child(1) .spec-val', row.location); text('.spec-item:nth-child(4) .spec-val', row.email); const image = document.querySelector('.profile-avatar-img'); if (image && row.profile_image) image.src = imageUrl(row.profile_image); document.querySelectorAll('.hero-socials a').forEach(link => { const title = (link.title || '').toLowerCase(); const value = title === 'github' ? row.github : title === 'linkedin' ? row.linkedin : title === 'instagram' ? row.instagram : title === 'facebook' ? row.facebook : title === 'email' ? (row.email ? 'mailto:' + row.email : '') : ''; if (value) link.href = value; }); }
  function settings(row) { if (!row) return; if (row.meta_title) document.title = row.meta_title; const meta = document.querySelector('meta[name="description"]'); if (meta && row.meta_description) meta.content = row.meta_description; const favicon = document.querySelector('link[rel="icon"]'); if (favicon && row.favicon_url) favicon.href = imageUrl(row.favicon_url); document.querySelectorAll('[data-site-name]').forEach(node => { node.textContent = row.website_title || 'Roshan Yadav'; }); const hero = document.querySelector('.hero-copy h1'); if (hero && row.hero_heading) hero.textContent = row.hero_heading; const description = document.querySelector('.hero-copy > p'); if (description && row.hero_description) description.textContent = row.hero_description; }
  async function load() { const results = await Promise.allSettled([published('projects'), published('skills'), published('services'), published('journey'), client.from('profile').select('*').eq('is_published', true).order('created_at', { ascending:false }).limit(1), client.from('site_settings').select('*').eq('is_published', true).order('created_at', { ascending:false }).limit(1)]); const value = index => results[index].status === 'fulfilled' && !results[index].value.error ? results[index].value.data || [] : []; ['projects','skills','services','journey'].forEach((table, index) => { collectionRows[table] = value(index); }); profile(value(4)[0]); settings(value(5)[0]); projects(collectionRows.projects); skills(collectionRows.skills); services(collectionRows.services); journey(collectionRows.journey); }
  function handleRealtimeChange(payload) { if (!realtimeTables.has(payload.table)) return; load().catch(error => console.error('Public CMS refresh failed:', error)); }
  let channel;
  function subscribe() { if (channel) client.removeChannel(channel); channel = client.channel('public-portfolio-content').on('postgres_changes', { event:'*', schema:'public' }, handleRealtimeChange).subscribe(status => { if (status === 'CHANNEL_ERROR' || status === 'TIMED_OUT') console.error('Public CMS realtime subscription:', status); }); }
  document.addEventListener('DOMContentLoaded', () => { load(); subscribe(); }, { once:true });
}());
