(function () {
  'use strict';
  const client = window.supabaseClient;
  const main = document.querySelector('.main');
  const overlay = document.getElementById('overlay');
  const dialogTitle = document.getElementById('dialogTitle');
  const dialogBody = document.getElementById('dialogBody');
  const bucket = 'portfolio-documents';
  if (!client || !main) return;
  const state = { view: null, rows: [], user: null };
  const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#039;' }[c]));
  const currentAdmin = async () => { const session = await client.auth.getSession(); const user = session.data.session?.user; if (!user) return null; const result = await client.rpc('is_admin'); return result.error || result.data !== true ? null : user; };
  const closeDialog = () => { if (overlay) overlay.hidden = true; };
  const fileType = row => { const type = String(row.file_type || '').toLowerCase(); const name = String(row.file_name || '').toLowerCase(); if (type.includes('pdf') || name.endsWith('.pdf')) return 'PDF'; if (type.includes('jpeg') || type.includes('jpg') || name.match(/\.jpe?g$/)) return 'JPG'; if (type.includes('png') || name.endsWith('.png')) return 'PNG'; if (name.endsWith('.docx')) return 'DOCX'; if (name.endsWith('.doc')) return 'DOC'; if (name.endsWith('.xlsx')) return 'XLSX'; if (name.endsWith('.xls')) return 'XLS'; return 'FILE'; };
  const size = bytes => { const value = Number(bytes || 0); if (!value) return 'Size unavailable'; if (value < 1024 * 1024) return Math.ceil(value / 1024) + ' KB'; return (value / 1024 / 1024).toFixed(1) + ' MB'; };
  const date = value => value ? new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : 'Date unavailable';
  const icon = row => fileType(row) === 'PDF' ? '📕' : ['JPG','PNG'].includes(fileType(row)) ? '🖼️' : '📄';
  function activate() { document.querySelectorAll('.view').forEach(view => { view.hidden = view !== state.view; }); document.querySelectorAll('[data-view]').forEach(button => button.classList.toggle('active', button.dataset.view === 'documents')); document.getElementById('title').textContent = 'Documents'; document.getElementById('side')?.classList.remove('open'); }
  function card(row) { return '<article class="document-admin-card"><div class="document-admin-head"><span class="document-file-icon">' + icon(row) + '</span><div class="document-admin-title"><h3>' + escape(row.title || row.file_name || 'Untitled document') + '</h3><p>' + escape(row.category || 'Uncategorized') + '</p></div><span class="document-type-badge">' + fileType(row) + '</span></div>' + (row.description ? '<p class="document-description">' + escape(row.description) + '</p>' : '') + '<div class="document-meta"><span>' + size(row.file_size) + '</span><span>Uploaded ' + escape(date(row.created_at)) + '</span></div><div class="document-actions"><button class="button" data-document-preview="' + row.id + '">Preview</button><button class="button" data-document-download="' + row.id + '">Download</button><button class="button" data-document-edit="' + row.id + '">Edit</button><button class="button danger" data-document-delete="' + row.id + '">Delete</button></div></article>'; }
  async function load() { if (!state.view) return; state.view.querySelector('[data-document-list]').innerHTML = '<div class="document-loading">Loading documents...</div>'; const result = await client.from('documents').select('id,title,description,category,file_path,file_name,file_type,file_size,created_at,updated_at,created_by').order('created_at', { ascending: false }); if (result.error) { console.error('Documents load failed:', result.error); state.view.querySelector('[data-document-list]').innerHTML = '<div class="document-empty">Unable to load documents. Please try again.</div>'; return; } state.rows = result.data || []; paint(); }
  function paint() { const list = state.view.querySelector('[data-document-list]'); list.innerHTML = state.rows.length ? state.rows.map(card).join('') : '<div class="document-empty"><span>📄</span><h3>No documents yet</h3><p>Upload your first document to get started.</p><button class="button primary" data-document-upload>＋ Upload Document</button></div>'; }
  function openForm(row) { dialogTitle.textContent = row ? 'Edit Document' : 'Upload Document'; dialogBody.innerHTML = '<form class="form document-edit-form" data-document-form><div class="document-form-grid"><label>Document Title *<input class="field" name="title" value="' + escape(row?.title || '') + '" required></label><label>Category *<input class="field" name="category" value="' + escape(row?.category || '') + '" required></label><label class="document-form-wide">Description<textarea class="field" name="description">' + escape(row?.description || '') + '</textarea></label><label class="document-form-wide">Replace File <input class="field" name="file" type="file" accept=".pdf,.doc,.docx,.xls,.xlsx,image/jpeg,image/png"><small class="muted">Optional. PDF, JPG, PNG, DOC, DOCX, XLS or XLSX up to 10 MB.</small></label></div><p class="status full" data-document-form-status></p><div class="document-form-actions"><button type="button" class="button" data-document-cancel>Cancel</button><button type="submit" class="button primary">Save Document</button></div></form>'; overlay.hidden = false; const form = dialogBody.querySelector('[data-document-form]'); form.querySelector('[data-document-cancel]').onclick = closeDialog; form.onsubmit = event => save(event, row); }
  async function save(event, row) { event.preventDefault(); const form = event.currentTarget; const status = form.querySelector('[data-document-form-status]'); const button = form.querySelector('button[type="submit"]'); const file = form.elements.file.files[0]; const allowed = ['application/pdf','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','image/jpeg','image/png']; if (file && (!allowed.includes(file.type) || file.size > 10 * 1024 * 1024)) { status.textContent = 'Choose a supported file up to 10 MB.'; status.className = 'status full error'; return; } button.disabled = true; button.textContent = 'Saving...'; let replacement = ''; try { const user = await currentAdmin(); if (!user) throw new Error('Admin session expired.'); let path = row?.file_path || null; if (file) { replacement = user.id + '/' + Date.now() + '-' + file.name.toLowerCase().replace(/[^a-z0-9._-]+/g, '-'); const upload = await client.storage.from(bucket).upload(replacement, file, { contentType: file.type, upsert: false }); if (upload.error) throw upload.error; path = replacement; } const payload = { title: form.elements.title.value.trim(), category: form.elements.category.value.trim(), description: form.elements.description.value.trim(), file_path: path, file_name: file?.name || row?.file_name || null, file_type: file?.type || row?.file_type || null, file_size: file?.size || row?.file_size || null }; const result = await client.from('documents').update(payload).eq('id', row.id); if (result.error) throw result.error; if (replacement && row.file_path) await client.storage.from(bucket).remove([row.file_path]); closeDialog(); await load(); } catch (error) { if (replacement) await client.storage.from(bucket).remove([replacement]); status.textContent = 'Could not save document. Please try again.'; status.className = 'status full error'; button.disabled = false; button.textContent = 'Save Document'; console.error('Document save failed:', error); } }
  async function signed(row, download) { const result = await client.storage.from(bucket).createSignedUrl(row.file_path, 60, download ? { download: row.file_name || row.title } : undefined); if (result.error) { console.error('Document link failed:', result.error); return; } window.open(result.data.signedUrl, '_blank', 'noopener,noreferrer'); }
  async function remove(row) { if (!window.confirm('Delete this document?')) return; const result = await client.from('documents').delete().eq('id', row.id); if (result.error) { alert('Could not delete document.'); return; } if (row.file_path) await client.storage.from(bucket).remove([row.file_path]); await load(); }
  async function show() { const user = await currentAdmin(); if (!user) { location.replace('../index.html#admin-login'); return; } state.user = user; if (!state.view) { state.view = document.createElement('section'); state.view.id = 'documentsView'; state.view.className = 'view'; main.appendChild(state.view); } state.view.innerHTML = '<div class="documents-admin-page"><div class="documents-admin-header"><div><span class="eyebrow">Private admin area</span><h2>Documents</h2><p class="muted">Manage your secure portfolio documents.</p></div><button class="button primary" data-document-upload>＋ Upload</button></div><div data-document-list class="documents-admin-grid"></div></div>'; activate(); await load(); }
  document.addEventListener('click', event => { const nav = event.target.closest('[data-view="documents"]'); const upload = event.target.closest('[data-upload="documents"], [data-document-upload]'); const action = event.target.closest('[data-document-preview], [data-document-download], [data-document-edit], [data-document-delete]'); if (!nav && !upload && !action) return; event.preventDefault(); event.stopImmediatePropagation(); if (nav) return show(); if (upload) return openForm(); const id = action.dataset.documentPreview || action.dataset.documentDownload || action.dataset.documentEdit || action.dataset.documentDelete; const row = state.rows.find(item => item.id === id); if (!row) return; if (action.matches('[data-document-preview]')) signed(row, false); else if (action.matches('[data-document-download]')) signed(row, true); else if (action.matches('[data-document-edit]')) openForm(row); else remove(row); }, true);
  if (location.hash === '#documents') show();
}());
