(function () {
  'use strict';
  const client = window.supabaseClient;
  const main = document.querySelector('.main');
  const overlay = document.getElementById('overlay');
  const dialogTitle = document.getElementById('dialogTitle');
  const dialogBody = document.getElementById('dialogBody');
  const buckets = ['portfolio-images', 'portfolio-gallery'];
  const bucket = 'portfolio-images';
  const state = { view: null, rows: [], user: null };
  if (!client || !main) return;
  const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#039;' }[c]));
  const date = value => value ? new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : 'Date unavailable';
  const currentAdmin = async () => { const session = await client.auth.getSession(); const user = session.data.session?.user; if (!user) return null; const result = await client.rpc('is_admin'); return result.error || result.data !== true ? null : user; };
  const close = () => { if (overlay) overlay.hidden = true; };
  const storagePath = (value, bucket) => { const path = String(value || ''); const marker = '/' + bucket + '/'; if (path.includes(marker)) return path.slice(path.indexOf(marker) + marker.length); return path.replace(new RegExp('^' + bucket + '/'), ''); };
  const signedUrl = async row => { if (!row?.file_path) return { error: new Error('Missing gallery file path') }; for (const bucket of buckets) { const result = await client.storage.from(bucket).createSignedUrl(storagePath(row.file_path, bucket), 300); if (!result.error) return { data: result.data, bucket }; } return { error: new Error('Gallery image is unavailable in configured storage buckets.') }; };
  function activate() { document.querySelectorAll('.view').forEach(view => { view.hidden = view !== state.view; }); document.querySelectorAll('[data-view]').forEach(button => button.classList.toggle('active', button.dataset.view === 'gallery')); document.getElementById('title').textContent = 'Gallery'; document.getElementById('side')?.classList.remove('open'); }
  function card(row) { const image = row.signedUrl ? '<img class="gallery-admin-thumb" src="' + escape(row.signedUrl) + '" alt="' + escape(row.title || 'Gallery image') + '" loading="lazy">' : '<div class="gallery-admin-thumb gallery-thumb-fallback">Image unavailable</div>'; return '<article class="gallery-admin-card"><div class="gallery-admin-media">' + image + '</div><div class="gallery-admin-copy"><div class="gallery-admin-title-row"><div><h3>' + escape(row.title || 'Untitled image') + '</h3><span class="gallery-category-badge">' + escape(row.category || 'Uncategorized') + '</span></div></div>' + (row.description ? '<p class="gallery-admin-description">' + escape(row.description) + '</p>' : '') + '<p class="gallery-admin-meta">Uploaded ' + escape(date(row.created_at)) + '</p><div class="gallery-admin-actions"><button class="button" data-gallery-preview="' + row.id + '">Preview</button><button class="button" data-gallery-edit="' + row.id + '">Edit</button><button class="button danger" data-gallery-delete="' + row.id + '">Delete</button></div></div></article>'; }
  async function load() { if (!state.view) return; state.view.querySelector('[data-gallery-list]').innerHTML = '<div class="gallery-list-loading">Loading gallery...</div>'; const result = await client.from('gallery').select('id,title,description,category,file_path,file_name,file_type,file_size,created_at,updated_at').order('created_at', { ascending: false }); if (result.error) { console.error('Gallery load failed:', result.error); state.view.querySelector('[data-gallery-list]').innerHTML = '<div class="gallery-list-empty">Unable to load gallery. Please try again.</div>'; return; } state.rows = result.data || []; await Promise.all(state.rows.map(async row => { const link = await signedUrl(row); row.signedUrl = link.error ? '' : link.data.signedUrl; row.storageBucket = link.bucket || buckets[0]; if (link.error) console.error('Gallery image URL failed:', link.error, row.file_path); })); paint(); }
  function paint() { const list = state.view.querySelector('[data-gallery-list]'); list.innerHTML = state.rows.length ? state.rows.map(card).join('') : '<div class="gallery-list-empty"><span>▧</span><h3>No gallery images yet</h3><p>Upload your first gallery image to get started.</p></div>'; }
  function preview(row) { if (!row.signedUrl) { alert('This image is unavailable right now.'); return; } dialogTitle.textContent = row.title || 'Gallery Preview'; dialogBody.innerHTML = '<div class="gallery-image-preview"><img src="' + escape(row.signedUrl) + '" alt="' + escape(row.title || 'Gallery image') + '"><button type="button" class="button" data-gallery-preview-close>Close</button></div>'; overlay.hidden = false; dialogBody.querySelector('[data-gallery-preview-close]').onclick = close; }
  function edit(row) { dialogTitle.textContent = 'Edit Gallery Image'; dialogBody.innerHTML = '<form class="form gallery-edit-form"><label>Image Title *<input class="field" name="title" value="' + escape(row.title) + '" required></label><label>Category *<select class="field" name="category" required>' + ['Personal','Project','Event','Education','Family','Other'].map(value => '<option' + (value === row.category ? ' selected' : '') + '>' + value + '</option>').join('') + '</select></label><label class="full">Description<textarea class="field" name="description">' + escape(row.description) + '</textarea></label><label class="full">Replace Image<input class="field" name="file" type="file" accept="image/jpeg,image/png,image/webp"><small class="muted">Optional. JPG, JPEG or PNG up to 10 MB.</small></label><p class="status full" data-gallery-edit-status></p><div class="gallery-edit-actions"><button type="button" class="button" data-gallery-edit-cancel>Cancel</button><button type="submit" class="button primary">Save Changes</button></div></form>'; overlay.hidden = false; const form = dialogBody.querySelector('form'); form.querySelector('[data-gallery-edit-cancel]').onclick = close; form.onsubmit = async event => { event.preventDefault(); const button = form.querySelector('button[type="submit"]'); const status = form.querySelector('[data-gallery-edit-status]'); const file = form.elements.file.files[0]; if (file && (!['image/jpeg','image/png','image/webp'].includes(file.type) || file.size > 10 * 1024 * 1024)) { status.textContent = 'Choose a JPG, PNG or WEBP image up to 10 MB.'; status.className = 'status full error'; return; } button.disabled = true; button.textContent = 'Saving...'; let replacement = ''; try { let path = row.file_path; if (file) { replacement = state.user.id + '/' + Date.now() + '-' + file.name.toLowerCase().replace(/[^a-z0-9._-]+/g, '-'); const upload = await client.storage.from(bucket).upload(replacement, file, { contentType: file.type, upsert: false }); if (upload.error) throw upload.error; path = replacement; } const update = await client.from('gallery').update({ title: form.elements.title.value.trim(), category: form.elements.category.value, description: form.elements.description.value.trim(), file_path: path, file_name: file?.name || row.file_name, file_type: file?.type || row.file_type, file_size: file?.size || row.file_size }).eq('id', row.id); if (update.error) throw update.error; if (replacement && row.file_path) await client.storage.from(bucket).remove([row.file_path]); close(); await load(); } catch (error) { if (replacement) await client.storage.from(bucket).remove([replacement]); status.textContent = 'Could not save gallery image.'; status.className = 'status full error'; button.disabled = false; button.textContent = 'Save Changes'; console.error('Gallery edit failed:', error); } }; }
  async function remove(row) { if (!window.confirm('Delete this gallery image?')) return; const result = await client.from('gallery').delete().eq('id', row.id); if (result.error) { alert('Could not delete gallery image.'); return; } if (row.file_path) await client.storage.from(row.storageBucket || bucket).remove([storagePath(row.file_path, row.storageBucket || bucket)]); await load(); }
  async function show() { const user = await currentAdmin(); if (!user) { location.replace('../index.html#admin-login'); return; } state.user = user; if (!state.view) { state.view = document.createElement('section'); state.view.id = 'galleryView'; state.view.className = 'view'; main.appendChild(state.view); } state.view.innerHTML = '<div class="gallery-admin-page"><div class="gallery-admin-header"><div><span class="eyebrow">Private admin area</span><h2>Gallery</h2><p class="muted">Manage your portfolio images.</p></div><button class="button primary" data-upload="gallery">＋ Upload Gallery Image</button></div><div data-gallery-list class="gallery-admin-list"></div></div>'; activate(); await load(); }
  document.addEventListener('click', event => { const nav = event.target.closest('[data-view="gallery"]'); const action = event.target.closest('[data-gallery-preview], [data-gallery-edit], [data-gallery-delete]'); if (!nav && !action) return; if (nav) { event.preventDefault(); event.stopImmediatePropagation(); return show(); } if (action) { event.preventDefault(); event.stopImmediatePropagation(); const row = state.rows.find(item => item.id === (action.dataset.galleryPreview || action.dataset.galleryEdit || action.dataset.galleryDelete)); if (!row) return; if (action.matches('[data-gallery-preview]')) preview(row); else if (action.matches('[data-gallery-edit]')) edit(row); else remove(row); } }, true);
  if (location.hash === '#gallery') show();
}());
