(function () {
  'use strict';
  const client = window.supabaseClient;
  const overlay = document.getElementById('overlay');
  const dialogTitle = document.getElementById('dialogTitle');
  const dialogBody = document.getElementById('dialogBody');
  const bucket = 'portfolio-images';
  if (!client || !overlay || !dialogTitle || !dialogBody) return;
  const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#039;' }[c]));
  const uuid = () => window.crypto?.randomUUID?.() || Date.now().toString(36) + Math.random().toString(36).slice(2);
  const close = () => { overlay.hidden = true; };
  const allowed = ['image/jpeg', 'image/png', 'image/webp'];
  function open() {
    dialogTitle.textContent = 'Upload Gallery Image';
    dialogBody.innerHTML = '<form class="form gallery-upload-editor" data-gallery-upload-form><p class="gallery-upload-intro">Add a polished image to your private portfolio gallery.</p><div class="gallery-upload-grid"><label>Image Title *<input class="field" name="title" placeholder="e.g. Mountain Trip" required></label><label>Category *<select class="field" name="category" required><option value="">Select category</option><option>Personal</option><option>Project</option><option>Event</option><option>Education</option><option>Family</option><option>Other</option></select></label><label class="gallery-upload-wide">Description <textarea class="field" name="description" placeholder="Add a short description..."></textarea></label></div><label class="gallery-dropzone"><input name="file" type="file" accept="image/jpeg,image/png,image/webp" required><span class="gallery-upload-icon">▧</span><strong>Drag &amp; drop image here</strong><small>or browse files</small><span>JPG · JPEG · PNG · WEBP · Max 10 MB</span></label><div class="gallery-preview" data-gallery-preview-panel><span class="gallery-preview-label">Image Preview</span><div class="gallery-preview-empty" data-gallery-preview-empty>Select an image to preview it</div><img data-gallery-preview alt="Selected gallery image" hidden><div class="gallery-preview-info"><strong data-gallery-file-name></strong><span data-gallery-file-size></span></div><button type="button" class="button" data-gallery-remove hidden>Remove / Replace</button></div><p class="status full" data-gallery-status role="status"></p><div class="gallery-upload-actions"><button type="button" class="button" data-gallery-cancel>Cancel</button><button type="submit" class="button primary">Upload</button></div></form>';
    overlay.hidden = false;
    const form = dialogBody.querySelector('[data-gallery-upload-form]'); const input = form.elements.file; const dropzone = form.querySelector('.gallery-dropzone'); const preview = form.querySelector('.gallery-preview'); const previewImage = form.querySelector('[data-gallery-preview]'); let objectUrl = '';
    const showFile = file => { if (objectUrl) URL.revokeObjectURL(objectUrl); if (!file) { objectUrl = ''; previewImage.removeAttribute('src'); previewImage.hidden = true; form.querySelector('[data-gallery-preview-empty]').hidden = false; form.querySelector('[data-gallery-remove]').hidden = true; return; } if (!allowed.includes(file.type) || file.size > 10 * 1024 * 1024) { form.querySelector('[data-gallery-status]').textContent = 'Choose a JPG, PNG or WEBP image up to 10 MB.'; form.querySelector('[data-gallery-status]').className = 'status full error'; input.value = ''; return; } objectUrl = URL.createObjectURL(file); previewImage.src = objectUrl; previewImage.hidden = false; form.querySelector('[data-gallery-preview-empty]').hidden = true; form.querySelector('[data-gallery-file-name]').textContent = file.name; form.querySelector('[data-gallery-file-size]').textContent = (file.size / 1024 / 1024).toFixed(1) + ' MB'; form.querySelector('[data-gallery-remove]').hidden = false; form.querySelector('[data-gallery-status]').textContent = ''; form.querySelector('[data-gallery-status]').className = 'status full'; };
    input.onchange = () => showFile(input.files[0]);
    form.querySelector('[data-gallery-remove]').onclick = () => { input.value = ''; showFile(null); };
    form.querySelector('[data-gallery-cancel]').onclick = () => { if (objectUrl) URL.revokeObjectURL(objectUrl); close(); };
    ['dragenter','dragover'].forEach(type => dropzone.addEventListener(type, event => { event.preventDefault(); dropzone.classList.add('dragging'); }));
    ['dragleave','drop'].forEach(type => dropzone.addEventListener(type, event => { event.preventDefault(); dropzone.classList.remove('dragging'); }));
    dropzone.addEventListener('drop', event => { const file = event.dataTransfer.files[0]; if (file && window.DataTransfer) { const transfer = new DataTransfer(); transfer.items.add(file); input.files = transfer.files; showFile(file); } });
    form.onsubmit = async event => { event.preventDefault(); const file = input.files[0]; const status = form.querySelector('[data-gallery-status]'); const button = form.querySelector('button[type="submit"]'); if (!file || !allowed.includes(file.type) || file.size > 10 * 1024 * 1024) { status.textContent = 'Choose a JPG, JPEG, PNG or WEBP image up to 10 MB.'; status.className = 'status full error'; return; } const session = await client.auth.getSession(); const user = session.data.session?.user; if (!user) { status.textContent = 'Admin session expired. Please sign in again.'; status.className = 'status full error'; return; } button.disabled = true; button.textContent = 'Uploading...'; const path = user.id + '/' + uuid() + '-' + file.name.toLowerCase().replace(/[^a-z0-9._-]+/g, '-'); try { const upload = await client.storage.from(bucket).upload(path, file, { contentType: file.type, upsert: false }); if (upload.error) throw upload.error; const insert = await client.from('gallery').insert({ title: String(form.elements.title.value).trim(), description: String(form.elements.description.value).trim(), category: form.elements.category.value, file_path: path, file_name: file.name, file_type: file.type, file_size: file.size, is_public: true, is_featured: false, is_published: true, created_by: user.id }); if (insert.error) throw insert.error; if (objectUrl) URL.revokeObjectURL(objectUrl); close(); document.querySelector('[data-view="gallery"]')?.click(); } catch (error) { await client.storage.from(bucket).remove([path]); status.textContent = 'Could not upload gallery image. Please try again.'; status.className = 'status full error'; button.disabled = false; button.textContent = 'Upload'; console.error('Gallery upload failed:', error); } };
  }
  document.addEventListener('click', event => { const button = event.target.closest('[data-upload="gallery"]'); if (!button) return; event.preventDefault(); event.stopImmediatePropagation(); open(); }, true);
}());
